
services:
  react-app:
    image: public.ecr.aws/c3y1y0l4/rcron/softeng-group7:latest  # Path to your React app Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - my-network

  api:
    image: public.ecr.aws/c3y1y0l4/rcron/softeng-group7-api:latest  # Path to your API Dockerfile
    ports:
      - "5000:5000"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge